Parameters:
  DBpwd:
    Description: Senha do Banco de dados
    Type: String
    NoEcho: true
  Subnet:
    Description: Subnet da Ec2
    Type: AWS::EC2::Subnet::Id
  InstanceName:
    Description: Nome da Instancia
    Type: String
  TipodeInstancia:
    Description: Maquina com WebServer
    Type: String
    Default: t3.medium
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.8xlarge
      - c5.12xlarge
      - c5.16xlarge
      - c5.24xlarge

Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-087855b6c8b59a9e4
      InstanceType: !Ref TipodeInstancia
      SubnetId: !Ref Subnet
      Tags:
        - Key: Name
          Value: !Ref InstanceName
      "UserData" : 
        Fn::Base64:
          !Sub |
          #!/bin/bash
          apt-get update
          apt-get install apache2 -y
          apt-get install mysql-server -y
          service apache2 start
          service mysqld stop
